#!/usr/bin/env python3
"""Read-only network-interface inventory + draft port-map generator.

Run this ON THE TARGET MACHINE (AlmaLinux dev/AMD) to capture the real
ifname / MAC / PCI-path of every physical Ethernet port, and emit a draft
config INI you can hand-edit into config/config_intel.ini (or config_amd.ini).

Safe: only reads /sys/class/net and calls `ip`. Changes nothing.
Python 3.9 compatible, stdlib only.

Usage:
    python3 tools/inventory.py                 # print table + draft INI
    python3 tools/inventory.py --board AMD-QC  # set [board] name in draft
"""
import argparse
import os
import sys

SYS_NET = "/sys/class/net"


def read(path):
    try:
        with open(path) as f:
            return f.read().strip()
    except OSError:
        return ""


def is_physical(iface):
    """Ethernet port backed by a real PCI/USB device (skip lo, virtual, bridges)."""
    if iface == "lo":
        return False
    # A physical NIC has a 'device' symlink under /sys/class/net/<if>/device
    return os.path.islink(os.path.join(SYS_NET, iface, "device"))


def pci_path(iface):
    """Stable PCI path, e.g. pci0000:00/0000:00:1c.0/0000:01:00.0 -> tail."""
    dev = os.path.join(SYS_NET, iface, "device")
    try:
        real = os.path.realpath(dev)
        # keep the PCI BDF (.../0000:01:00.3)
        return real.split("/devices/")[-1]
    except OSError:
        return ""


def collect():
    rows = []
    for iface in os.listdir(SYS_NET):
        if not is_physical(iface):
            continue
        base = os.path.join(SYS_NET, iface)
        rows.append({
            "iface": iface,
            "mac": read(os.path.join(base, "address")),
            "driver": os.path.basename(
                os.path.realpath(os.path.join(base, "device", "driver"))
            ) if os.path.exists(os.path.join(base, "device", "driver")) else "",
            "carrier": read(os.path.join(base, "carrier")) == "1",
            "speed": read(os.path.join(base, "speed")),
            "pci": pci_path(iface),
        })
    # Stable, repeatable ordering by PCI path.
    rows.sort(key=lambda r: r["pci"])
    return rows


def print_table(rows):
    print("Physical Ethernet ports (sorted by PCI path):\n")
    hdr = "{:<12} {:<18} {:<10} {:<7} {:<8} {}".format(
        "IFNAME", "MAC", "DRIVER", "LINK", "SPEED", "PCI-PATH")
    print(hdr)
    print("-" * len(hdr))
    for r in rows:
        print("{:<12} {:<18} {:<10} {:<7} {:<8} {}".format(
            r["iface"], r["mac"], r["driver"],
            "UP" if r["carrier"] else "down",
            (r["speed"] + "M") if r["speed"].isdigit() else "-",
            r["pci"]))


def print_draft(rows, board):
    print("\n" + "=" * 60)
    print("Draft config INI  (edit LAN order to match physical labels!):")
    print("=" * 60)
    print("[board]")
    print("name = %s" % board)
    print("description = generated by inventory.py - VERIFY port order\n")
    print("[port_map]")
    for i, r in enumerate(rows, 1):
        print("LAN%d = %s    # MAC %s | %s | %s" % (
            i, r["iface"], r["mac"], r["driver"], r["pci"]))
    print("\n# To confirm which physical jack is which, blink each port's LED:")
    for r in rows:
        print("#   sudo ethtool -p %s 10     # watch which bracket port blinks" % r["iface"])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--board", default="INTEL-DEV")
    args = ap.parse_args()
    rows = collect()
    if not rows:
        print("No physical Ethernet ports found.", file=sys.stderr)
        return 1
    print_table(rows)
    print_draft(rows, args.board)
    print("\nFound %d physical port(s)." % len(rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
